<script type="" src="/easytrip/PUBLIC/module/Portfolio/js/uploader.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/jui/jui-1-11-0/eicra/jquery-ui.custom.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/js/backend/common.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/vendor/scripts/js/slicker.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/vendor/scripts/js/dropdown.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/js/backend/jquery.hoverpulse.js"></script>
<script type="text/javascript" src="/easytrip/PUBLIC/templates/backend/default/vendor/scripts/js/ddslick.js"></script>
<script type="text/javascript" src="/easytrip/PUBLIC/templates/backend/default/vendor/scripts/js/easyResponsiveTabs.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/kendo/src/js/kendo.web.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/kendo/js/cultures/kendo.culture.en.min.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/kendo/js/cultures/kendo.culture.en-US.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/gsap/TweenMax.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/api.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/resizeable.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/joinable.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/custom.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/backend/default/assets/js/demo.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/jquery-ui/blue/jquery-ui.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/js/responsive-tabs.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/js/top-bar.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/js/scroll.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/js/scripts.min.js"></script>
<script type="" src="/easytrip/PUBLIC/templates/frontend/tour_default/vendor/scripts/js/tipso.min.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/js/frontend/slicker.min.js"></script>
<script type="" src="/easytrip/PUBLIC/vendor/scripts/js/frontend/common.min.js"></script>